name: Waka Readme

on:
  # for manual workflow trigger
  workflow_dispatch:
  schedule:
    # runs at 12 AM UTC (5:30 AM IST)
    - cron: "0 */12 * * *"

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
        # this action name
      - uses: athul/waka-readme@master # do NOT replace with anything else
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }} # required
          ### meta
          API_BASE_URL: https://wakatime.com/api # optional
          ### content
          SHOW_TITLE: true # optional
          SECTION_NAME: My Waka-time stats # optional
          BLOCKS: "#â–ˆ" # optional
          TIME_RANGE: last_30_days # optional
          LANG_COUNT: 7 # optional
          SHOW_TIME: true # optional
          SHOW_TOTAL: true # optional
          SHOW_MASKED_TIME: true # optional
          STOP_AT_OTHER: true # optional
          ### commit
          COMMIT_MESSAGE: Updated waka-readme graph with new metrics # optional
          TARGET_BRANCH: master # optional
          TARGET_PATH: README.md # optional
          COMMITTER_NAME: crllect # optional
          COMMITTER_EMAIL: crllect@proton.me # optional
          AUTHOR_NAME: crllect # optional
          AUTHOR_EMAIL: crllect@proton.me # optional
          # you can populate email-id with secrets instead
